import type { Author } from "@/types";

export const authors: Author[] = [
  {
    id: "weber",
    slug: "weber",
    name: "Max Weber",
    years: "1864-1920",
    tagline:
      "Pourquoi on obéit à une règle plutôt qu'à un homme.",
    keywords: ["Bureaucratie", "Autorité légale", "Rationalisation"],
    bio: "Max Weber est l'un des fondateurs de la sociologie moderne. Il a développé une typologie des formes de domination légitime (traditionnelle, charismatique, rationnelle-légale) pour comprendre pourquoi des individus obéissent à un ordre sans y être contraints par la force. Son analyse de la bureaucratie comme organisation fondée sur des règles écrites, une hiérarchie des fonctions et une compétence spécialisée a profondément marqué la sociologie des organisations. Il voyait dans la rationalisation croissante des sociétés occidentales un processus à la fois efficace et porteur de risques de déshumanisation, qu'il a résumé par l'image de la « cage d'acier ».",
    themes: ["bureaucratie-regles", "autorite-domination"],
    domain: "organizational-sociology",
  },
  {
    id: "merton",
    slug: "merton",
    name: "Robert K. Merton",
    years: "1910-2003",
    tagline:
      "Ce qu'une règle produit sans que personne l'ait voulu.",
    keywords: ["Fonctions latentes", "Déplacement des buts", "Conformité"],
    bio: "Robert K. Merton est un sociologue fonctionnaliste américain, connu pour avoir distingué les fonctions manifestes (les effets voulus et reconnus d'une institution) des fonctions latentes (ses effets non voulus et souvent non perçus). Il a appliqué cette distinction à l'étude des bureaucraties, montrant comment la discipline et la conformité aux règles, utiles à l'origine, peuvent se transformer en rigidité et en fin en soi : c'est le phénomène qu'il a nommé le déplacement des buts. Ses travaux ont ouvert la voie à une analyse critique mais nuancée des dysfonctions bureaucratiques, sans rejeter l'idée wébérienne de rationalité organisationnelle.",
    themes: ["bureaucratie-regles", "comportements-organisationnels"],
    domain: "organizational-sociology",
  },
  {
    id: "simon",
    slug: "simon",
    name: "Herbert A. Simon",
    years: "1916-2001",
    tagline:
      "On ne choisit pas le meilleur, mais le premier acceptable.",
    keywords: ["Rationalité limitée", "Satisficing", "Décision"],
    bio: "Herbert A. Simon a montré que les décideurs, dans les organisations comme ailleurs, ne disposent ni du temps, ni de l'information, ni des capacités cognitives nécessaires pour identifier et comparer toutes les solutions possibles à un problème. Il a forgé le concept de rationalité limitée (bounded rationality) pour décrire cette situation, et celui de satisficing pour désigner la recherche d'une solution simplement satisfaisante plutôt qu'optimale. Ses travaux, récompensés par le prix Nobel d'économie en 1978, ont fondé une approche réaliste de la prise de décision organisationnelle, reprise ensuite par James March avec qui il a collaboré.",
    themes: ["decision"],
    domain: "organizational-sociology",
  },
  {
    id: "march",
    slug: "march",
    name: "James G. March",
    years: "1928-2018",
    tagline:
      "Décider tient souvent moins du plan que du hasard.",
    keywords: ["Modèle de la poubelle", "Exploration", "Ambiguïté"],
    bio: "James G. March a prolongé et approfondi les travaux de Herbert Simon sur la rationalité limitée. Avec Michael Cohen et Johan Olsen, il a proposé le modèle de la « poubelle » (garbage can model), selon lequel dans certaines organisations les problèmes, les solutions, les participants et les occasions de choix circulent de façon relativement indépendante et ne se rencontrent souvent que par hasard. Il a également théorisé la tension entre exploration de nouvelles possibilités et exploitation des compétences existantes, un arbitrage central pour comprendre l'apprentissage et le changement organisationnels.",
    themes: ["decision", "changement-organisationnel"],
    domain: "organizational-sociology",
  },
  {
    id: "crozier",
    slug: "crozier",
    name: "Michel Crozier",
    years: "1922-2013",
    tagline:
      "Le pouvoir se loge là où la règle n'a pas tout prévu.",
    keywords: ["Zone d'incertitude", "Analyse stratégique", "Cercle vicieux"],
    bio: "Michel Crozier est le fondateur, avec Erhard Friedberg, de l'analyse stratégique des organisations en France. Dans « Le Phénomène bureaucratique » (1963), il montre à partir d'enquêtes de terrain que même dans les bureaucraties les plus rigides, les acteurs conservent une marge de liberté qu'ils utilisent stratégiquement pour défendre leurs intérêts. Cette marge naît du contrôle de zones d'incertitude que les règles formelles ne parviennent jamais totalement à éliminer. Il a également décrit un « cercle vicieux bureaucratique » où la multiplication des règles, censée réduire l'incertitude, en crée de nouvelles et alimente la rigidité du système.",
    themes: ["pouvoir", "bureaucratie-regles"],
    domain: "organizational-sociology",
  },
  {
    id: "friedberg",
    slug: "friedberg",
    name: "Erhard Friedberg",
    years: "né en 1942",
    tagline:
      "L'ordre d'une organisation se négocie, il ne se décrète pas.",
    keywords: ["Système d'action concret", "Coopération", "Régulation"],
    bio: "Erhard Friedberg a co-écrit avec Michel Crozier « L'Acteur et le système » (1977), ouvrage fondateur de l'analyse stratégique des organisations. Il y développe le concept de système d'action concret : l'ensemble des relations effectives, souvent informelles, par lesquelles des acteurs interdépendants régulent conjointement leur coopération au-delà des règles formelles. Ses travaux insistent sur le caractère toujours construit et négocié de l'ordre organisationnel, jamais simplement imposé d'en haut ni réductible à l'organigramme.",
    themes: ["pouvoir", "organisation-formelle-reelle"],
    domain: "organizational-sociology",
  },
  {
    id: "hirschman",
    slug: "hirschman",
    name: "Albert O. Hirschman",
    years: "1915-2012",
    tagline:
      "Partir, protester ou se taire, face au déclin.",
    keywords: ["Défection", "Prise de parole", "Loyauté"],
    bio: "Albert O. Hirschman a publié en 1970 « Exit, Voice, and Loyalty », un ouvrage qui dépasse le cadre strictement économique pour éclairer le fonctionnement de toute organisation confrontée à une baisse de qualité ou de performance perçue par ses membres. Il y distingue la défection (exit, quitter l'organisation), la prise de parole (voice, protester pour obtenir un changement) et la loyauté (loyalty, rester malgré l'insatisfaction). Son apport majeur est de montrer que ces trois options interagissent : une forte loyauté peut retarder la défection et donner du temps à la prise de parole, mais aussi étouffer toute contestation.",
    themes: ["reaction-insatisfaction"],
    domain: "organizational-sociology",
  },
  {
    id: "argyris",
    slug: "argyris",
    name: "Chris Argyris",
    years: "1923-2013",
    tagline:
      "Corriger l'erreur, ou questionner la règle qui l'a produite.",
    keywords: ["Simple boucle", "Double boucle", "Routines défensives"],
    bio: "Chris Argyris a consacré une grande partie de sa carrière, notamment avec Donald Schön, à l'étude de l'apprentissage organisationnel. Il distingue l'apprentissage en simple boucle, qui corrige une erreur en ajustant les moyens sans remettre en cause les objectifs ou les hypothèses de départ, de l'apprentissage en double boucle, qui va jusqu'à questionner ces présupposés eux-mêmes. Il a également étudié les « routines défensives », ces comportements individuels et collectifs qui protègent les acteurs d'un examen critique gênant mais bloquent, ce faisant, l'apprentissage profond de l'organisation.",
    themes: ["apprentissage-organisationnel"],
    domain: "organizational-sociology",
  },
  {
    id: "desrosieres",
    slug: "desrosieres",
    name: "Alain Desrosières",
    years: "1940-2013",
    tagline:
      "Compter suppose d'abord de s'accorder sur ce qui compte.",
    keywords: ["Conventions d'équivalence", "Socio-histoire de la statistique", "Quantification"],
    bio: "Alain Desrosières est un statisticien, sociologue et historien de la statistique français, polytechnicien et administrateur de l'INSEE, où il a notamment dirigé la division des études sociales. Il est le fondateur d'un champ de recherche original, la socio-histoire de la statistique et de la quantification, qui étudie comment les catégories statistiques (professions, chômage, classes sociales...) sont construites par des conventions sociales avant de pouvoir être mesurées. Son ouvrage majeur, « La Politique des grands nombres » (1993), retrace la formation historique de l'État statistique en France et dans d'autres pays. Avec Laurent Thévenot, il a coécrit un ouvrage de référence sur les nomenclatures socioprofessionnelles (1988). Sa thèse centrale est que quantifier suppose d'abord de convenir : établir des équivalences entre des objets ou des personnes hétérogènes, avant que la mesure proprement dite ne puisse s'appliquer à ces catégories désormais stabilisées.",
    themes: ["quantification-operation-sociale"],
    domain: "measurement-theory",
  },
  {
    id: "swain",
    slug: "swain",
    name: "Alan D. Swain",
    years: "1923-2021",
    tagline:
      "Chiffrer la chance qu'un opérateur se trompe, faute de mieux.",
    keywords: ["THERP", "Probabilité d'erreur humaine", "Fiabilité humaine"],
    bio: "Alan D. Swain est un ingénieur en facteurs humains américain qui a rejoint les Sandia National Laboratories en 1961, où il a travaillé sur la fiabilité des systèmes d'armement puis des centrales nucléaires. Il y développe, à partir d'une communication de 1962, la Technique for Human Error Rate Prediction (THERP), première méthode structurée pour quantifier la probabilité qu'un opérateur commette une erreur dans une tâche donnée. Cette approche est formalisée dans le rapport WASH-1400 (1975) puis dans le « Handbook of Human Reliability Analysis » (1983), publié pour la Commission de régulation nucléaire américaine avec son coauteur Henry E. Guttmann. Faute de données d'erreur réelles suffisantes, les probabilités du Handbook combinent données expérimentales et jugement d'expert. Cité comme l'auteur le plus référencé du champ de l'analyse de la fiabilité humaine, Swain reste associé à THERP, qui demeure la méthode la plus utilisée dans ce domaine.",
    themes: ["erreur-humaine-et-fiabilite"],
    domain: "human-factors",
  },
  {
    id: "ombredane",
    slug: "ombredane",
    name: "André Ombredane",
    years: "1898-1958",
    tagline:
      "Décomposer le travail en gestes, est-ce encore décrire un travail ?",
    keywords: ["Analyse du travail", "Psychologie du travail", "Ergonomie francophone"],
    bio: "André Ombredane est un médecin et psychologue français, agrégé de philosophie et docteur en médecine, qui a enseigné la psychologie expérimentale à l'université de Rio de Janeiro puis à l'université libre de Bruxelles. Figure fondatrice de la psychologie du travail francophone, il est surtout connu pour « L'analyse du travail » (1955), écrit avec Jean-Marie Faverge, ouvrage qui a durablement structuré le champ. L'expression « analyse du travail » circulait toutefois déjà avant ce livre, notamment chez Faverge lui-même dès 1952, où il évoque les domaines « où l'on pratique l'analyse du travail ». Ombredane a surtout attiré l'attention sur le risque propre à toute décomposition analytique du travail en éléments séparés : en fragmentant l'observation, on peut perdre de vue les structures concrètes qui organisent réellement le comportement au travail.",
    themes: ["tache-et-activite"],
    domain: "activity-ergonomics",
  },
  {
    id: "weill-fassina",
    slug: "weill-fassina",
    name: "Annie Weill-Fassina",
    tagline:
      "Travailler ensemble ne suffit pas à faire un collectif sur lequel compter.",
    keywords: ["Ergonomie de l'activité", "Collectif de travail", "Processus cognitifs"],
    bio: "Annie Weill-Fassina est une enseignante-chercheuse française, figure de la seconde génération de l'ergonomie francophone. Elle a débuté au Centre d'études et de recherches psychologiques avant de rejoindre l'École pratique des hautes études, où elle a exercé au sein du Laboratoire de psychologie du travail dirigé par Jacques Leplat (1969-1989) puis du Laboratoire d'ergonomie physiologique et cognitive dirigé par Antoine Laville (1989-2005). Ses travaux portent sur les processus cognitifs engagés dans l'activité de travail de nombreux métiers, à la croisée de l'ergonomie et de la psychologie. Elle a codirigé en 2000 un ouvrage de référence sur le travail collectif en ergonomie francophone et est associée à la distinction entre travail collectif — la manière dont plusieurs personnes s'y prennent ensemble — et collectif de travail, ce qui s'en construit dans la durée par la transmission et la confiance partagée. Membre honoraire de la SELF depuis 2002, elle a reçu le titre de Fellow de l'IEA en 2024.",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "dugue",
    slug: "dugue",
    name: "Bernard Dugué",
    years: "né en 1955",
    tagline:
      "Deux façons de faire au lieu d'une, c'est déjà un rempart contre l'usure du travail.",
    keywords: ["Marge de manœuvre", "Troubles musculo-squelettiques", "Ergonomie de l'activité"],
    bio: "Bernard Dugué, sociologue et ergonome européen, est chercheur au Laboratoire d'ergonomie des systèmes complexes (LESC) de l'université Bordeaux 2, devenu depuis l'équipe ergonomie des systèmes complexes de l'IMS-Bordeaux INP. Ses travaux portent sur le dialogue social dans l'entreprise, le travail d'encadrement et les démarches de transformation des situations de travail. Il a notamment étudié comment l'intensification du travail réduit la marge de manœuvre dont disposent les opérants, et comment cette réduction dégrade leur rapport à l'activité. En 2003, il cosigne avec Fabien Coutarel et François Daniellou l'article qui donne à la notion de marge de manœuvre une définition explicite : la possibilité, pour un opérateur, de faire autrement pour faire face aux aléas. Le texte distingue deux régimes, en situation de conception et en situation de fonctionnement, et fait de cette marge la pièce centrale d'un modèle de prévention des troubles musculo-squelettiques.",
    themes: ["regulation-et-marges"],
    domain: "activity-ergonomics",
  },
  {
    id: "billings",
    slug: "billings",
    name: "Charles E. Billings",
    years: "1929-2010",
    tagline:
      "Automatiser sans jamais dessaisir le pilote de la conduite de son vol.",
    keywords: ["Automatisation centrée sur l'humain", "Facteurs humains aéronautiques", "Sécurité aérienne"],
    bio: "Charles E. Billings est un médecin américain, spécialiste de médecine aéronautique, formé comme flight surgeon dans l'US Air Force avant de rejoindre en 1973 le NASA Ames Research Center, où il passe dix-neuf ans, notamment comme responsable du bureau de recherche sur les systèmes aériens puis chercheur senior de la division facteurs humains. Il est l'architecte du NASA Aviation Safety Reporting System (ASRS), programme de signalement volontaire et confidentiel des incidents aériens devenu opérationnel en 1976 et resté quasiment inchangé depuis. À partir des données de l'ASRS, il s'intéresse dans les années 1980 à l'automatisation croissante des cockpits : avec Curtis Graeber, il présente en octobre 1989 les premiers principes de ce qu'il appelle l'« automatisation centrée sur l'humain », une philosophie de conception visant à ce que l'automatisation demeure un outil au service du pilote sans jamais lui retirer l'autorité sur son vol. Il formalise cette doctrine dans un mémorandum NASA de 1996.",
    themes: ["automatisation-et-conception-cognitive"],
    domain: "human-factors",
  },
  {
    id: "faita",
    slug: "faita",
    name: "Daniel Faïta",
    tagline:
      "Faire dialoguer un professionnel avec les images de son propre travail.",
    keywords: ["Clinique de l'activité", "Autoconfrontation croisée", "Genre professionnel"],
    bio: "Daniel Faïta est professeur de linguistique, longtemps rattaché à l'université de Provence (aujourd'hui Aix-Marseille université), où il a dirigé des recherches à l'IUFM et travaillé au sein d'un laboratoire d'ergologie. Il collabore étroitement avec Yves Clot et l'équipe Clinique de l'activité du Cnam, à Paris. Ensemble, ils mettent au point la méthode de l'autoconfrontation croisée : un professionnel est d'abord confronté aux images de sa propre activité, puis à celles d'un collègue placé dans la même situation, ce qui fait émerger des aspects du métier qui échappent à la conscience immédiate de celui qui les vit. C'est dans ce cadre de recherche qu'il contribue, avec Clot, Gabriel Fernandez et Livia Scheller, à distinguer le genre professionnel — les manières de faire tacitement partagées par un collectif de métier — du style, la façon dont chaque professionnel les reprend et les infléchit dans l'action. Ses travaux portent en particulier sur l'analyse de l'activité enseignante.",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "norman",
    slug: "norman",
    name: "Donald A. Norman",
    years: "né en 1935",
    tagline:
      "Une erreur d'utilisation révèle le plus souvent un défaut de conception.",
    keywords: ["Design centré sur l'humain", "Erreurs et glissements", "Rétroaction"],
    bio: "Donald A. Norman est un psychologue cognitiviste et ingénieur américain, professeur émérite de l'université de Californie à San Diego, où il a dirigé le département de psychologie puis celui des sciences cognitives avant de fonder le Design Lab. Après un passage chez Apple comme vice-président de la technologie avancée, il cofonde en 1998 le cabinet Nielsen Norman Group avec Jakob Nielsen. Il est surtout connu pour « The Design of Everyday Things », ouvrage qui popularise l'idée qu'une erreur d'utilisation révèle le plus souvent un défaut de conception plutôt qu'une faute de l'utilisateur. Dans un rapport de 1979 sur les « slips », des actions exécutées sans être voulues, il déplace vers le champ de l'action un terme reçu de la tradition freudienne du lapsus. Il a également montré que l'automatisation, quand elle prive l'opérateur d'une rétroaction continue sur l'état du système, peut aggraver plutôt que réduire le risque d'erreur.",
    themes: ["erreur-humaine-et-fiabilite", "automatisation-et-conception-cognitive"],
    domain: "human-factors",
  },
  {
    id: "campbell",
    slug: "campbell",
    name: "Donald T. Campbell",
    years: "1916-1996",
    tagline:
      "Un indicateur qu'on utilise pour décider finit par se corrompre.",
    keywords: ["Indicateurs", "Quasi-expérimentation", "Épistémologie évolutionnaire"],
    bio: "Donald T. Campbell est un psychologue social et méthodologue américain, l'un des chercheurs les plus cités du XXe siècle en sciences sociales. Professeur notamment à l'Ohio State University, à l'université de Chicago puis à Northwestern, il a marqué la méthodologie des sciences sociales par ses travaux sur les devis quasi-expérimentaux (avec Julian Stanley) et sur la validité des mesures, avec la matrice multitrait-multiméthode conçue avec Donald Fiske. Il a également développé une épistémologie évolutionnaire fondée sur la variation aveugle et la sélection. Dans un texte où il examine l'usage des indicateurs sociaux, il énonce, au pluriel et sans leur donner de nom, des « lois pessimistes » selon lesquelles tout indicateur quantitatif, dès lors qu'il sert de base à des décisions importantes, subit des pressions de corruption qui faussent le processus social qu'il est censé mesurer. C'est cette observation, rebaptisée après coup « loi de Campbell » par la littérature qui l'a reprise, qui a fait de lui une référence incontournable de la théorie de la mesure.",
    themes: ["effets-retour-de-la-mesure"],
    domain: "measurement-theory",
  },
  {
    id: "didier",
    slug: "didier",
    name: "Emmanuel Didier",
    years: "né en 1970",
    tagline:
      "Les nombres gouvernent aussi par les émotions qu'ils suscitent.",
    keywords: ["Statactivisme", "Sociologie de la quantification", "Benchmarking"],
    bio: "Emmanuel Didier est un sociologue français, spécialiste de la sociologie de la quantification. Formé à l'École normale supérieure et à l'ENSAE, puis docteur de l'École des Mines de Paris sous la direction de Bruno Latour, il est directeur de recherche au CNRS, rattaché au Centre Maurice Halbwachs (ENS/EHESS), et rédacteur en chef de la revue Statistique et société. Il a cofondé avec la politiste Isabelle Bruno et l'artiste Julien Prévieux le courant du « statactivisme », qui étudie comment les statistiques peuvent aussi servir à contester le pouvoir plutôt qu'à seulement l'exercer. Avec Isabelle Bruno, dont il crédite lui-même les travaux communs, il a notamment étudié le benchmarking comme technique de gouvernement fondée sur des cibles chiffrées présentées comme un simple constat du réel, ce qui désarme la négociation politique. Dans un article ultérieur dont il est seul auteur, il propose le terme de « datademic » pour décrire comment les chiffres de la pandémie ont suscité des émotions collectives avant d'être mobilisés pour contrôler ces mêmes émotions.",
    themes: ["audit-evaluation-reddition-de-comptes", "quantification-operation-sociale"],
    domain: "measurement-theory",
  },
  {
    id: "coutarel",
    slug: "coutarel",
    name: "Fabien Coutarel",
    tagline:
      "Avoir le choix du geste, c'est déjà se protéger.",
    keywords: ["Marge de manœuvre", "Troubles musculo-squelettiques", "Ergonomie de l'activité"],
    bio: "Fabien Coutarel est ergonome, professeur des universités à l'Université Clermont Auvergne, où il codirige le laboratoire ACTé et dirige le master Ingénierie et Ergonomie de l'Activité Physique. Docteur en ergonomie (2004) et habilité à diriger des recherches, il travaille sur la conception de situations de travail capacitantes, la prévention des troubles musculo-squelettiques et des risques psychosociaux, ainsi que sur l'évaluation des interventions ergonomiques. En 2003, avec François Daniellou et Bernard Dugué, il cosigne un article qui donne à la notion de marge de manœuvre — reçue de l'ergonomie francophone plutôt que forgée par eux — une définition explicite, en la distinguant selon qu'elle s'exerce en situation de conception ou de fonctionnement, et en fait un élément central d'un modèle de prévention des troubles musculo-squelettiques : plus une situation de travail laisse à l'opérateur plusieurs façons possibles d'atteindre un même résultat, mieux il peut faire face aux aléas sans que sa santé en pâtisse.",
    themes: ["regulation-et-marges"],
    domain: "activity-ergonomics",
  },
  {
    id: "bourgeois",
    slug: "bourgeois",
    name: "Fabrice Bourgeois",
    tagline:
      "La tâche n'est pas l'horizon de l'ergonomie, mais son moyen.",
    keywords: ["Tâche et activité", "Prescription", "Troubles musculo-squelettiques"],
    bio: "Fabrice Bourgeois est ergonome consultant, longtemps associé au cabinet Omnia (Amiens) avant de rejoindre le cabinet Concilio. Spécialisé dans la prévention des troubles musculo-squelettiques, il a beaucoup travaillé sur la filière viande et sur les effets du lean management dans l'organisation industrielle, accompagnant au tournant des années 2000 des médecins et des conseillers de la Mutualité sociale agricole. Avec François Hubault, enseignant-chercheur en ergonomie à l'université Paris 1, il cosigne en 2004 un article qui prend position dans un débat structurant de la discipline : plutôt que de faire de la tâche prescrite l'horizon que l'ergonomie devrait aider à mieux tenir, les deux auteurs en font un simple moyen au service de l'activité réelle, qu'aucun modèle prescriptif ne peut entièrement anticiper. Cette distinction entre tâche et activité, fondatrice de l'ergonomie francophone, ne leur appartient pas ; ce qui leur revient est la position prise dans cette dispute et l'inversion de la hiérarchie habituelle entre les deux termes.",
    themes: ["tache-et-activite"],
    domain: "activity-ergonomics",
  },
  {
    id: "jany-catrice",
    slug: "jany-catrice",
    name: "Florence Jany-Catrice",
    years: "née en 1964",
    tagline:
      "Mesurer la qualité, jusqu'à en faire une doctrine totale.",
    keywords: ["Indicateurs de richesse", "Économie de la qualité", "Critique de la mesure"],
    bio: "Florence Jany-Catrice est une économiste française, professeure des universités, spécialiste de la socio-économie du travail, des services et de la mesure de la richesse. Formée à l'université de Lille, au Collège d'Europe de Bruges et à l'université Johns-Hopkins, elle mène l'essentiel de sa carrière au laboratoire CLERSÉ (CNRS, Lille), avant de rejoindre l'université de Rouen-Normandie. Avec l'économiste Jean Gadrey, elle a co-fondé le Forum pour d'autres indicateurs de richesse (FAIR) et développé une critique socio-historique des indicateurs macroéconomiques usuels — PIB, indices de prix, indicateurs de performance — qu'elle analyse comme des conventions sociales situées plutôt que des mesures neutres. C'est dans ce sillage qu'elle forge, par analogie avec la « qualité totale » telle que l'a critiquée Christophe Dejours, l'expression « performance totale » pour décrire un régime d'évaluation des politiques publiques où l'appréciation plurielle d'une action cède la place à un chiffre unique et décontextualisé. Elle a notamment publié Les Nouveaux Indicateurs de richesse (avec Jean Gadrey, 2005) et La performance totale : nouvel esprit du capitalisme ? (2012).",
    themes: ["audit-evaluation-reddition-de-comptes"],
    domain: "measurement-theory",
  },
  {
    id: "daniellou",
    slug: "daniellou",
    name: "François Daniellou",
    years: "né en 1955",
    tagline:
      "Concevoir un poste, c'est déjà décider de ce qui restera possible d'y faire.",
    keywords: ["Marge de manœuvre", "Simulation de l'activité future", "Conception des situations de travail"],
    bio: "François Daniellou, né en 1955 à Nantes, est un ergonome français formé à l'École centrale de Paris puis, à partir de 1980, à l'ergonomie au laboratoire du Conservatoire national des arts et métiers dirigé par Alain Wisner et Antoine Laville. Docteur en ergonomie en 1985, il devient professeur à l'université Bordeaux 2 puis à l'École nationale supérieure de cognitique de Bordeaux INP, où il dirige le département Ergonomie des systèmes complexes. Ses travaux portent sur la prise en compte du travail et de la santé dans la conception des situations de travail et des organisations, en particulier face aux troubles musculo-squelettiques et aux risques psychosociaux. Il a contribué, avec Fabien Coutarel et Bernard Dugué, à formaliser la notion de marge de manœuvre comme condition de la santé au travail, et a porté des démarches de simulation de l'activité future permettant d'éprouver, dès la conception, les formes possibles du travail à venir. De 2015 à 2019, il a été directeur scientifique de l'ICSI et de la FonCSI. L'Association internationale d'ergonomie lui a décerné son Outstanding Educator Award en 2009.",
    themes: ["regulation-et-marges", "activite-instrumentee-et-conception"],
    domain: "activity-ergonomics",
  },
  {
    id: "hubault",
    slug: "hubault",
    name: "François Hubault",
    tagline:
      "La tâche n'est pas l'horizon du travail, elle n'en est que le moyen.",
    keywords: ["Ergologie", "Tâche et activité", "Intervention ergonomique"],
    bio: "François Hubault est un ergonome et économiste français, professeur puis professeur émérite à l'université Paris 1 Panthéon-Sorbonne, où il a dirigé le département Ergonomie et écologie humaine. Il intervient également au Conservatoire national des arts et métiers et anime le laboratoire d'intervention et de recherche ATEMIS. Il a codirigé avec Pierre Cazamian et Monique Noulin le Traité d'ergonomie (1996) et coordonné l'ouvrage collectif Le métier d'ergonome (2002). Engagé dans le développement de la démarche ergologique portée par Yves Schwartz, il défend une conception de l'intervention où l'analyse du travail ne se sépare pas d'une interrogation sur la pratique même de l'ergonome. Avec Fabrice Bourgeois, il a pris position, dans un article de 2004, pour une ergonomie qui fait de la tâche un simple moyen de l'activité plutôt que son horizon à atteindre — retournant ainsi l'ordre habituel dans lequel cette distinction, fondatrice de la discipline, est généralement pensée.",
    themes: ["tache-et-activite"],
    domain: "activity-ergonomics",
  },
  {
    id: "fernandez",
    slug: "fernandez",
    name: "Gabriel Fernandez",
    tagline:
      "Ce que le métier enseigne sans l'écrire, chacun le retouche en le faisant.",
    keywords: ["Clinique de l'activité", "Genre professionnel et style", "Médecine du travail"],
    bio: "Gabriel Fernandez est médecin et psychologue du travail français. Après avoir exercé comme médecin du travail dans les secteurs ferroviaire (SNCF), aéronautique et métallurgique, puis à l'Assistance publique-Hôpitaux de Paris, il participe aux travaux de l'équipe de clinique de l'activité et à l'enseignement de la chaire de psychologie du travail du Conservatoire national des arts et métiers, aux côtés d'Yves Clot. Son approche articule étroitement médecine du travail et psychologie clinique du travail, autour de la question du pouvoir d'agir des salariés sur leur propre activité. Il est l'un des quatre signataires, avec Yves Clot, Daniel Faïta et Livia Scheller, d'un article de 2000 qui définit collectivement les notions de genre professionnel — les manières de faire qu'un métier impose tacitement à ceux qui l'exercent — et de style, la façon dont chaque professionnel retouche ce genre en agissant. Il a notamment publié Nous, conducteurs de train (2003) et Soigner le travail : itinéraire d'un médecin du travail (2009).",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "klein",
    slug: "klein",
    name: "Gary Klein",
    years: "né en 1944",
    tagline:
      "L'expert ne compare pas deux options, il reconnaît une situation.",
    keywords: ["Décision reconnue d'emblée", "Prise de décision naturaliste", "Expertise professionnelle"],
    bio: "Gary Klein est un psychologue américain né en 1944, figure fondatrice du courant de la prise de décision naturaliste (naturalistic decision making). Après une thèse en psychologie expérimentale à l'université de Pittsburgh et des recherches menées pour l'US Air Force, il fonde en 1978 Klein Associates, où il étudie des professionnels confrontés à des décisions réelles sous contrainte de temps : pompiers, pilotes, personnel médical. Il en tire le modèle de la décision reconnue d'emblée (recognition-primed decision, RPD) : l'expert ne compare pas plusieurs options entre elles, il reconnaît dans la situation une dynamique familière, en déduit d'emblée une conduite plausible, puis l'évalue mentalement en l'imaginant se dérouler. Ce modèle, dont le nom apparaît dès une étude de 1986 menée avec Roberta Calderwood et Anne Clinton-Cirocco auprès de chefs d'intervention sur incendie, a renouvelé la compréhension de l'expertise et influencé la formation à la décision dans l'armée américaine. Klein a par ailleurs développé la méthode du « pre-mortem » pour anticiper les échecs de projet.",
    themes: ["decision-et-conscience-de-la-situation"],
    domain: "human-factors",
  },
  {
    id: "guttmann",
    slug: "guttmann",
    name: "Henry E. Guttmann",
    tagline:
      "Mettre un chiffre sur la chance qu'un opérateur se trompe.",
    keywords: ["THERP", "Probabilité d'erreur humaine", "Fiabilité humaine"],
    bio: "Henry E. Guttmann est un ingénieur en fiabilité humaine ayant travaillé au Sandia National Laboratories (Albuquerque, Nouveau-Mexique). Il cosigne avec Alan D. Swain le Handbook of Human Reliability Analysis with Emphasis on Nuclear Power Plant Applications (NUREG/CR-1278, 1983), publié pour la Nuclear Regulatory Commission américaine. Cet ouvrage de référence met en forme la méthode THERP (Technique for Human Error Rate Prediction), mise au point par Swain dès 1962 et employée depuis pour évaluer la fiabilité des opérateurs dans les centrales nucléaires. Le manuel fournit des tables de probabilités d'erreur humaine (Human Error Probabilities) servant d'indices de base pour une tâche donnée ; faute de données d'incidents réels en nombre suffisant, la plupart de ces valeurs combinent données expérimentales et jugement d'expert. Le sigle THERP et son développement initial sont antérieurs à la collaboration avec Guttmann et rapportés par le texte à Swain seul, mais le Handbook de 1983 est bien un travail cosigné : la page de titre et la fiche bibliographique officielle du rapport (NRC Form 335) portent les deux noms, « Alan D. Swain and Henry E. Guttmann ».",
    themes: ["erreur-humaine-et-fiabilite"],
    domain: "human-factors",
  },
  {
    id: "bruno",
    slug: "bruno",
    name: "Isabelle Bruno",
    tagline:
      "Quand les chiffres se donnent pour le réel, il n'y a plus rien à négocier.",
    keywords: ["Benchmarking", "Sociologie de la quantification", "Statactivisme"],
    bio: "Isabelle Bruno est politiste, professeure des universités à l'Université de Lille, où elle dirige le CERAPS (UMR CNRS). Sa thèse de doctorat, soutenue en 2006 à Sciences Po Paris, porte sur le benchmarking comme technique de coordination intergouvernementale au sein de l'Union européenne (« Déchiffrer l'Europe compétitive »). Elle poursuit ensuite ses recherches dans le champ de la sociologie de la quantification, notamment autour du projet ANR « Benchmark » (2009-2012) et d'un séjour de recherche à l'université Cornell consacré à la généalogie du benchmarking. Avec Emmanuel Didier, elle publie en 2013 Benchmarking. L'État sous pression statistique, qui analyse comment cet outil assigne aux acteurs publics des cibles chiffrées présentées comme un décalque neutre du réel, alors qu'elles sont en fait fabriquées, et dont l'autorité, en se donnant pour indiscutable, désarme la négociation politique. Ses travaux ont contribué au courant du « statactivisme », l'usage critique et militant de la statistique. Elle travaille depuis 2014 sur les inégalités socio-environnementales liées à l'appropriation du littoral.",
    themes: ["audit-evaluation-reddition-de-comptes"],
    domain: "measurement-theory",
  },
  {
    id: "leplat",
    slug: "leplat",
    name: "Jacques Leplat",
    years: "1921-2023",
    tagline:
      "Ce que dit la procédure ne dit jamais tout ce qu'il faut faire.",
    keywords: ["Analyse du travail", "Régulation de l'activité", "Fiabilité humaine"],
    bio: "Jacques Leplat (1921-2023) est l'un des fondateurs de l'ergonomie et de la psychologie du travail francophones. Il dirige de 1966 à 1989 le laboratoire de psychologie du travail de l'École pratique des hautes études, qu'il réoriente vers l'analyse de l'activité, en dialogue avec la théorie soviétique de l'activité, la psychologie du développement piagétienne et le cognitivisme naissant. Membre fondateur de la Société d'ergonomie de langue française, il reçoit en 1990 le prix de l'International Ergonomics Association pour l'ensemble de sa contribution à la recherche en ergonomie. Son œuvre porte notamment sur la distinction entre travail prescrit et travail réel, sur la régulation de l'activité, par laquelle l'opérateur ajuste son action à l'écart entre but et résultat tout en poursuivant des fins propres (santé, confort), et sur l'analyse des documents prescripteurs (consignes, procédures, modes d'emploi), dont il a montré qu'ils n'explicitent jamais complètement la tâche à accomplir. Retraité actif dès 1989, il a continué de publier jusqu'en 2020. Parmi ses ouvrages : Introduction à la psychologie du travail (1977, avec Xavier Cuny) et La psychologie ergonomique (1980).",
    themes: ["tache-et-activite", "regulation-et-marges"],
    domain: "activity-ergonomics",
  },
  {
    id: "reason",
    slug: "reason",
    name: "James Reason",
    years: "1938-2025",
    tagline:
      "Il faut plusieurs défenses trouées, et alignées, pour qu'un accident passe.",
    keywords: ["Défaillances actives", "Conditions latentes", "Fiabilité organisationnelle"],
    bio: "James Reason (1938-2025) est un psychologue britannique, professeur à l'Université de Manchester, spécialiste de l'erreur humaine dans les systèmes complexes. Son ouvrage Human Error (1990) distingue les défaillances actives, erreurs commises au contact direct du système, des conditions latentes, des failles organisationnelles enfouies qui restent longtemps sans effet visible. Cette distinction est devenue le socle de l'analyse des accidents organisationnels : un accident survient rarement d'une seule cause, mais de l'alignement de plusieurs défenses trouées. Cette image, connue sous le nom de « modèle du fromage suisse », a été popularisée par ses travaux sans qu'il en revendique la paternité : il a lui-même précisé, dans une note ultérieure cosignée avec Erik Hollnagel et Jean Paries, ne pas être à l'origine de l'appellation, probablement due à Rob Lee. Ses travaux ont durablement marqué la sécurité aérienne, nucléaire et hospitalière ; il a été fait Commandeur de l'Empire britannique en 2003 pour ses contributions à la réduction des risques dans le secteur de la santé.",
    themes: ["erreur-humaine-et-fiabilite"],
    domain: "human-factors",
  },
  {
    id: "reynaud",
    slug: "reynaud",
    name: "Jean-Daniel Reynaud",
    years: "1926-2019",
    tagline:
      "L'ordre d'une organisation naît de deux régulations qui se répondent, pas d'une seule.",
    keywords: ["Régulation de contrôle", "Régulation autonome", "Théorie de la régulation sociale"],
    bio: "Jean-Daniel Reynaud (1926-2019) est un sociologue français, professeur honoraire de sociologie du travail au Conservatoire national des arts et métiers (Cnam), fondateur de la théorie de la régulation sociale. Il montre que l'ordre dans une organisation ne procède jamais d'un seul principe : à la régulation de contrôle, portée par la direction et formalisée dans les règlements, répond une régulation autonome, élaborée par les exécutants eux-mêmes pour organiser leur propre coopération. Ces règles autonomes ne sont ni un simple désordre ni un système informel spontané : elles constituent une stratégie collective face au contrôle hiérarchique. Reynaud a développé cette théorie depuis les années 1950 et l'a systématisée dans son ouvrage majeur, Les Règles du jeu : l'action collective et la régulation sociale (1989), où il défend l'idée qu'un ordre social résulte toujours de la rencontre, jamais définitivement acquise, entre ces deux logiques de régulation. Son approche a durablement renouvelé la sociologie du travail et des organisations en France.",
    themes: ["organisation-formelle-reelle", "pouvoir"],
    domain: "organizational-sociology",
  },
  {
    id: "faverge",
    slug: "faverge",
    name: "Jean-Marie Faverge",
    years: "1912-1988",
    tagline:
      "Décrire le travail élément par élément, est-ce encore décrire ce qui s'y fait ?",
    keywords: ["Analyse du travail", "Ergonomie francophone", "Situations de travail"],
    bio: "Jean-Marie Faverge (1912-1988) est un ergonome français, agrégé de mathématiques, qui débute sa carrière comme assistant du psychologue André Ombredane à l'Institut de psychologie de Paris, où il enseigne la statistique et les débuts de l'adaptation du travail à l'homme. En 1959, il devient directeur du laboratoire de psychologie de l'Université libre de Bruxelles, où il développe l'ergonomie et participe à des recherches pour la Communauté européenne du charbon et de l'acier. Avec Ombredane, il publie en 1955 L'Analyse du travail, ouvrage cosigné qui pose des bases de référence pour l'analyse du travail dans le champ ergonomique francophone. Membre fondateur de la Société d'ergonomie de langue française (SELF), Faverge a contribué à faire de la description systématique des situations de travail un objet d'étude scientifique à part entière, ouvrant la voie aux débats ultérieurs sur ce qu'une décomposition du travail en éléments isolés peut faire perdre du comportement réel observé.",
    themes: ["tache-et-activite"],
    domain: "activity-ergonomics",
  },
  {
    id: "rasmussen",
    slug: "rasmussen",
    name: "Jens Rasmussen",
    years: "1926-2018",
    tagline:
      "Un geste, une règle ou un raisonnement : trois façons différentes de se tromper.",
    keywords: ["Modèle SRK", "Ingénierie cognitive", "Interfaces écologiques"],
    bio: "Jens Rasmussen (1926-2018) est un ingénieur danois, chercheur au Risø National Laboratory où il dirige le département d'électronique de 1962 à 1987, avant d'occuper de 1987 à 1992 une chaire d'ingénierie cognitive partagée entre Risø et l'Université technique du Danemark. Spécialiste de la sûreté des installations nucléaires et de l'interaction homme-machine, il développe à partir de ses travaux des années 1970 un modèle distinguant trois niveaux de comportement selon le degré de contrôle cognitif qu'ils requièrent : les routines fondées sur l'habileté (skills), l'application de règles apprises (rules) et le raisonnement à partir de connaissances (knowledge), regroupés plus tard sous le sigle SRK. Avec Kim Vicente, il formule ensuite le cadre théorique de la conception écologique d'interface, qui vise à soutenir chacun de ces niveaux sans forcer inutilement le raisonnement là où un réflexe suffirait. Ses travaux ont profondément influencé l'ingénierie cognitive et l'analyse des accidents dans les systèmes complexes.",
    themes: ["automatisation-et-conception-cognitive", "erreur-humaine-et-fiabilite"],
    domain: "human-factors",
  },
  {
    id: "acker",
    slug: "acker",
    name: "Joan Acker",
    years: "1924-2016",
    tagline:
      "Neutre en apparence, un poste suppose toujours un corps et une vie.",
    keywords: ["Organisation genrée", "Corps sans attaches", "Régimes d'inégalité"],
    bio: "Joan Acker (1924-2016) est une sociologue américaine, professeure à l'université de l'Oregon à partir de 1967, figure majeure de la sociologie féministe de la deuxième vague. Dans « Hierarchies, Jobs, Bodies: A Theory of Gendered Organizations » (1990), elle soutient que le genre n'est pas un facteur extérieur venant perturber des organisations par ailleurs neutres : la définition même d'un poste de travail, de sa hiérarchie et de ses exigences, présuppose un travailleur sans charges familiales, disponible à plein temps, pendant qu'un tiers assure hors de l'organisation le travail de reproduction et de soin. Elle identifie plusieurs processus par lesquels le genre s'inscrit dans les structures, la culture, les interactions et les identités au travail. Dans ses travaux ultérieurs, elle élargit ce cadre à la notion de « régimes d'inégalité », articulant genre, classe et race au sein des organisations.",
    themes: ["organisation-formelle-reelle"],
    domain: "organizational-sociology",
  },
  {
    id: "olsen",
    slug: "olsen",
    name: "Johan P. Olsen",
    years: "né en 1939",
    tagline:
      "Ce qui est approprié compte autant que ce qui est efficace.",
    keywords: ["Anarchie organisée", "Ambiguïté", "Nouvel institutionnalisme"],
    bio: "Johan P. Olsen (né en 1939 à Tromsø) est un politiste norvégien, professeur à l'université de Bergen puis fondateur du centre de recherche ARENA à l'université d'Oslo en 1994, l'une des figures majeures du « nouvel institutionnalisme » en science politique. Avec James March, il coécrit « Ambiguity and Choice in Organizations » (1976), où est formulé, avec Michael D. Cohen, le modèle de la poubelle (garbage can model) : dans une « anarchie organisée » — aux buts ambigus, à la technologie floue et à la participation fluctuante — problèmes et solutions ne se rencontrent souvent que par la coïncidence de leur présence au même moment devant la même occasion de choix. Ce modèle, bien qu'habituellement rangé sous le seul nom de March, reste le fruit d'un travail collectif avec Cohen et Olsen. Olsen a ensuite prolongé cette veine avec March dans « Rediscovering Institutions » (1989), en mettant en avant la « logique de l'approprié » qui guide l'action organisationnelle autant que le calcul des conséquences.",
    themes: ["decision"],
    domain: "organizational-sociology",
  },
  {
    id: "freeman",
    slug: "freeman",
    name: "John Freeman",
    years: "1944-2008",
    tagline:
      "La fiabilité d'une organisation se paie en rigidité.",
    keywords: ["Écologie des organisations", "Inertie structurelle", "Sélection organisationnelle"],
    bio: "John H. Freeman (1944-2008) est un sociologue américain des organisations, professeur d'entrepreneuriat à la Haas School of Business de l'université de Californie à Berkeley, après des travaux menés à Stanford. Avec Michael T. Hannan, il fonde à la fin des années 1970 l'écologie des populations organisationnelles, qui déplace l'explication du changement organisationnel de l'adaptation individuelle des organisations vers la sélection au niveau des populations. Dans « The Population Ecology of Organizations » (1977) puis « Structural Inertia and Organizational Change » (1984), Hannan et Freeman soutiennent que ce qui rend une organisation fiable et redevable auprès de ses parties prenantes — reproduire sa structure à l'identique — est aussi ce qui limite sa capacité à changer en profondeur : cette inertie structurelle devient le trait sur lequel opère la sélection de l'environnement, plutôt que l'adaptation volontaire. Ces travaux communs, habituellement rangés sous l'écologie des populations plutôt que sous l'un des deux noms, valent à Hannan et Freeman le prix Max Weber de l'Association américaine de sociologie en 1992.",
    themes: ["changement-organisationnel"],
    domain: "organizational-sociology",
  },
  {
    id: "zinnes",
    slug: "zinnes",
    name: "Joseph L. Zinnes",
    tagline:
      "La vérité d'un nombre ne doit rien au choix de l'unité.",
    keywords: ["Signification numérique", "Invariance d'échelle", "Théorie de la mesure"],
    bio: "Joseph L. Zinnes est un psychologue mathématicien américain, longtemps rattaché au département de psychologie de l'université d'Indiana à Bloomington, où ses travaux ont notamment porté sur la perception des couleurs et les modèles de décision. Il est surtout connu en théorie de la mesure pour sa collaboration avec Patrick Suppes : leur chapitre « Basic Measurement Theory », publié en 1963 dans le premier volume du Handbook of Mathematical Psychology dirigé par R. Duncan Luce, Robert Bush et Eugene Galanter, formalise le « problème de la signification » (meaningfulness problem). Selon Suppes et Zinnes, un énoncé portant sur des mesures n'a de sens que si sa valeur de vérité reste constante sous les transformations d'échelle admissibles — une propriété qui porte sur l'énoncé entier, et non sur l'opération numérique qu'il emploie. Ce cadre s'appuie lui-même sur des travaux antérieurs de Suppes avec Dana Scott (1958) sur la mesure fondamentale.",
    themes: ["theorie-des-echelles-et-nombres"],
    domain: "measurement-theory",
  },
  {
    id: "arnoud",
    slug: "arnoud",
    name: "Justine Arnoud",
    tagline:
      "Une ressource donnée n'est pas encore un pouvoir d'agir.",
    keywords: ["Environnement capacitant", "Capabilité", "Ergonomie constructive"],
    bio: "Justine Arnoud est professeure des sciences de gestion à l'IAE Paris-Est (Institut de recherche en gestion) et docteure en ergonomie du Conservatoire national des arts et métiers (CNAM), où elle a soutenu en 2013 une thèse dirigée par Pierre Falzon, « Conception organisationnelle : pour des interventions capacitantes ». Elle y défend l'idée que la conception ou la reconception des organisations doit se penser dans une perspective développementale, en s'appuyant sur l'approche par les capabilités d'Amartya Sen. Dans un article de 2013 cosigné avec Pierre Falzon, elle précise ce que suppose un « environnement capacitant » : une ressource mise à disposition ne devient un pouvoir d'agir qu'à condition d'être convertie en capabilité, conversion qui exige des conditions particulières. C'est cette étape de conversion, distincte des notions de capabilité et d'environnement capacitant elles-mêmes empruntées à des travaux antérieurs, qui constitue son apport propre à l'ergonomie constructive.",
    themes: ["regulation-et-marges"],
    domain: "activity-ergonomics",
  },
  {
    id: "messing",
    slug: "messing",
    name: "Karen Messing",
    years: "née en 1943",
    tagline:
      "À poste égal, le même travail n'est pas toujours le même travail.",
    keywords: ["Genre et travail", "Santé au travail", "Analyse du travail"],
    bio: "Karen Messing, née en 1943 à Springfield (Massachusetts), est une généticienne et ergonome canadienne. Formée à Harvard puis à l'Université McGill, elle a enseigné les sciences biologiques à l'Université du Québec à Montréal de 1976 à 2008, où elle est aujourd'hui professeure émérite. D'abord spécialiste de génétique moléculaire, elle réoriente ses recherches vers la santé au travail dans les années 1980, en étudiant notamment l'exposition aux rayonnements des technologues en radiologie, un métier très féminisé. En 1985, elle cofonde avec Donna Mergler le Centre de recherche interdisciplinaire sur le bien-être, la santé, la société et l'environnement (CINBIOSE). Son article de 1999, publié en son seul nom mais qui synthétise dix années d'enquêtes menées avec un collectif de recherche et des centrales syndicales québécoises, montre qu'à emploi identique, les tâches et contraintes réelles peuvent différer selon le sexe des opérateurs — un constat qui a renouvelé l'analyse du travail. Officier de l'Ordre du Canada, elle est notamment l'autrice des « Souffrances invisibles » et du « Deuxième corps ».",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "vicente",
    slug: "vicente",
    name: "Kim J. Vicente",
    tagline:
      "Une interface pensée pour que l'œil raisonne autant qu'il regarde.",
    keywords: ["Ergonomie cognitive", "Conception écologique", "Systèmes sociotechniques"],
    bio: "Kim J. Vicente est un ingénieur canadien, professeur de génie mécanique et industriel à l'Université de Toronto, où il a fondé et dirigé le Cognitive Engineering Laboratory. Docteur de l'Université de l'Illinois à Urbana-Champaign (1991), il devient à 34 ans le plus jeune professeur titulaire de l'histoire de son université. Ses recherches portent sur la conception de technologies adaptées à des systèmes sociotechniques complexes — centrales nucléaires, aviation, réseaux, médecine. Avec Jens Rasmussen, qu'il a côtoyé au laboratoire Risø au Danemark, il publie en 1992 un article qui formule pour la première fois une théorie de la conception écologique d'interface (ecological interface design), en s'appuyant sur la taxonomie des niveaux cognitifs élaborée par Rasmussen. Il est l'auteur de « Cognitive Work Analysis » (1999) et de « The Human Factor » (2003), ouvrage de vulgarisation sur les rapports entre humains et technologie.",
    themes: ["automatisation-et-conception-cognitive"],
    domain: "human-factors",
  },
  {
    id: "scheller",
    slug: "scheller",
    name: "Livia Scheller",
    tagline:
      "Ce que le métier apprend sans jamais l'écrire.",
    keywords: ["Clinique de l'activité", "Genre professionnel", "Instruction au sosie"],
    bio: "Livia Scheller est psychologue du travail et clinicienne de l'activité, enseignante-chercheuse au Centre de recherche sur le travail et le développement (CRTD) du Conservatoire national des arts et métiers (CNAM). Proche collaboratrice d'Yves Clot, elle joue un rôle marquant dans l'histoire de la clinique de l'activité, notamment en contribuant, lors de sa thèse soutenue en 2003, au développement de la méthode de « l'instruction au sosie ». Elle cosigne en 2000, avec Yves Clot, Daniel Faïta et Gabriel Fernandez, un article qui distingue le genre professionnel — ces manières de faire tacitement imposées par un métier — du style, la façon dont chaque professionnel les retouche en agissant ; les deux notions y sont posées au nom du collectif, sans part individuelle attribuée. Elle a notamment publié « La force collective de l'individu » (2022), qui articule récits de travail et relecture d'auteurs classiques comme Vygotski et Winnicott.",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "staveland",
    slug: "staveland",
    name: "Lowell E. Staveland",
    tagline:
      "Le nom que l'ergonomie cite sans qu'aucun texte ne le signe seul.",
    keywords: ["NASA-TLX", "Charge de travail", "Facteurs humains"],
    bio: "Lowell E. Staveland est associé à l'université d'État de San José (San Jose State University) et a participé, aux côtés du groupe de recherche en performance humaine du centre Ames de la NASA, aux travaux ayant conduit à la NASA Task Load Index (NASA-TLX). Il cosigne avec Sandra G. Hart le chapitre de référence « Development of NASA-TLX (Task Load Index): Results of Empirical and Theoretical Research » (1988), qui synthétise trois années de simulations en laboratoire menées pour identifier les facteurs de variation de la charge de travail subjective selon les tâches. Peu d'éléments biographiques le concernant sont disponibles au-delà de cette collaboration : son nom n'apparaît pas comme auteur du manuel technique NASA-TLX lui-même, document collectif publié sans signature individuelle par le Human Performance Research Group, mais seulement dans ce chapitre cosigné avec Hart et dans la bibliographie qui l'accompagne, où les deux noms sont associés à une étude de validation alors à paraître.",
    themes: ["charge-et-vigilance"],
    domain: "human-factors",
  },
  {
    id: "cuvelier",
    slug: "cuvelier",
    name: "Lucie Cuvelier",
    tagline:
      "Anticiper, c'est doter l'équipe des ressources pour tenir l'imprévu.",
    keywords: ["Résilience organisationnelle", "Gestion des ressources", "Ergonomie de l'activité"],
    bio: "Lucie Cuvelier est ergonome, docteure en ergonomie du Conservatoire national des arts et métiers (Cnam), où elle soutient en 2011 une thèse dirigée par Pierre Falzon consacrée à la gestion des ressources de l'activité et à la résilience en anesthésie pédiatrique. Maîtresse de conférences en ergonomie à l'université Paris 8 à partir de 2012, elle est aujourd'hui rattachée au laboratoire LINEACT du CESI. Ses travaux portent sur la gestion des risques et la sécurité dans les systèmes sociotechniques complexes, en particulier dans le champ de la santé. La même année que sa thèse, elle publie avec Pierre Falzon un chapitre qui reprend la définition de la résilience proposée par Erik Hollnagel et la prolonge par une lecture centrée sur les ressources : anticiper, pour une équipe, ce n'est pas seulement prévoir les événements possibles, c'est concevoir une enveloppe de situations qu'elle pourra effectivement tenir compte tenu de ses ressources, notamment intrinsèques, plutôt que de s'en remettre aux seuls protocoles.",
    themes: ["securite-et-resilience"],
    domain: "human-factors",
  },
  {
    id: "strathern",
    slug: "strathern",
    name: "Marilyn Strathern",
    years: "née en 1941",
    tagline:
      "Un bon indicateur cesse de l'être dès qu'on le prend pour objectif.",
    keywords: ["Culture de l'audit", "Anthropologie de la mesure", "Nouveau management public"],
    bio: "Marilyn Strathern est une anthropologue sociale britannique, formée à Girton College (Cambridge) sous la direction d'Edmund Leach. Après un terrain mené chez les Hagen de Papouasie-Nouvelle-Guinée et des postes à l'Australian National University puis à l'université de Manchester, elle occupe la chaire William Wyse d'anthropologie sociale à Cambridge de 1993 à 2008, et dirige Girton College de 1998 à 2009. Ses travaux les plus connus portent sur la parenté, le genre et les techniques de reproduction, notamment « The Gender of the Gift » (1988) et « After Nature » (1992). À partir des années 1990, elle tourne le regard anthropologique vers les pratiques d'audit et d'évaluation qui se généralisent dans les universités et administrations britanniques, dans des travaux réunis notamment sous le titre « Audit Cultures » (2000). Elle y montre qu'un indicateur érigé en objectif cesse de mesurer fidèlement ce qu'il était censé représenter, en reprenant et resserrant à son compte une observation déjà formulée par Keith Hoskin.",
    themes: ["effets-retour-de-la-mesure"],
    domain: "measurement-theory",
  },
  {
    id: "endsley",
    slug: "endsley",
    name: "Mica R. Endsley",
    tagline:
      "Percevoir, comprendre, anticiper : trois niveaux avant toute décision.",
    keywords: ["Conscience de la situation", "SAGAT", "Facteurs humains"],
    bio: "Mica R. Endsley est une ingénieure américaine spécialiste des facteurs humains, docteure en génie industriel et des systèmes de l'université de Californie du Sud (1990), après un master à Purdue et un premier diplôme à Texas Tech. Professeure associée de génie industriel, puis fondatrice et présidente-directrice générale de SA Technologies (1997-2013), elle a occupé le poste de Chief Scientist de l'US Air Force. Elle est l'autrice de la définition en trois niveaux de la conscience de la situation (situation awareness) — perception des éléments de la situation, compréhension de leur signification, projection de leur état à court terme — formulée dans un article de 1988 puis développée dans son article fondateur de 1995, « Toward a Theory of Situation Awareness in Dynamic Systems ». Elle a aussi conçu la méthode SAGAT (Situation Awareness Global Assessment Technique) pour mesurer objectivement cette conscience de la situation, aujourd'hui largement utilisée mais dont le statut scientifique reste discuté au sein même de la communauté des facteurs humains.",
    themes: ["decision-et-conscience-de-la-situation"],
    domain: "human-factors",
  },
  {
    id: "cohen",
    slug: "cohen",
    name: "Michael D. Cohen",
    years: "1945-2013",
    tagline:
      "Modéliser ce qui semble n'obéir à aucun plan d'ensemble.",
    keywords: ["Modèle de la poubelle", "Anarchies organisées", "Systèmes complexes"],
    bio: "Michael D. Cohen est un politiste et théoricien des organisations américain, professeur à l'université du Michigan où il occupe la chaire William D. Hamilton de systèmes complexes, d'information et de politiques publiques. Avec James G. March et Johan P. Olsen, il propose en 1972 le modèle de la « poubelle » (garbage can model) : dans une organisation aux buts ambigus et à la participation fluctuante, dite « anarchie organisée », problèmes et solutions circulent indépendamment et ne se rencontrent souvent que par coïncidence temporelle. Ce concept, coécrit à parts égales par les trois auteurs, reste néanmoins généralement rattaché au nom de March. Cohen a ensuite orienté ses travaux vers la modélisation des systèmes complexes et la simulation multi-agents, notamment avec Robert Axelrod, pour étudier l'émergence de la coopération et des routines organisationnelles. Il s'est aussi intéressé, en fin de carrière, à la mémoire procédurale des organisations et aux transmissions de responsabilité entre équipes hospitalières.",
    themes: ["decision"],
    domain: "organizational-sociology",
  },
  {
    id: "sauder",
    slug: "sauder",
    name: "Michael Sauder",
    tagline:
      "On ne regarde pas un classement, on s'y ajuste.",
    keywords: ["Réactivité", "Classements", "Commensuration"],
    bio: "Michael Sauder est sociologue, professeur à l'université de l'Iowa, où il dirige le département de sociologie et de criminologie. Formé à l'université Northwestern, il s'intéresse aux organisations, à l'inégalité et à la théorie sociale, avec un intérêt particulier pour les effets des classements sur l'enseignement supérieur. Avec Wendy Espeland, à qui il attribue explicitement une contribution égale, il développe la notion de réactivité des mesures publiques : un classement ne décrit pas seulement ce qu'il évalue, il le transforme, via deux mécanismes — l'autoréalisation des attentes et la commensuration, qui rend comparables des objets hétérogènes. Ce cadre, qu'ils reprennent et prolongent à partir des travaux de Donald T. Campbell et de Carol A. Heimer, distingue trois effets typiques : maximiser un critère, redéfinir son identité en fonction de lui, ou le manipuler directement. Leurs travaux, réunis dans l'ouvrage Engines of Anxiety (2016), ont compté parmi les sources ayant motivé le retrait de plusieurs grandes facultés de droit américaines du classement U.S. News.",
    themes: ["effets-retour-de-la-mesure"],
    domain: "measurement-theory",
  },
  {
    id: "hannan",
    slug: "hannan",
    name: "Michael T. Hannan",
    years: "né en 1943",
    tagline:
      "Ce qui rend une organisation fiable est aussi ce qui la fige.",
    keywords: ["Écologie des organisations", "Inertie structurelle", "Sélection"],
    bio: "Michael T. Hannan est sociologue des organisations, professeur émérite à la Stanford Graduate School of Business, après des postes à Stanford puis à Cornell. Avec John H. Freeman, il fonde en 1977 l'écologie des populations organisationnelles, qui applique à l'analyse des organisations les logiques de variation, sélection et rétention plutôt que les seules stratégies individuelles. Dans un article de 1984 devenu classique, les deux auteurs soutiennent que la fiabilité et la responsabilité (accountability) attendues d'une organisation reposent sur la reproduction fidèle de sa structure ; cette même reproduction produit l'inertie structurelle, un handicap face au changement que seule la sélection — la disparition des formes inadaptées — permet de trancher. Le concept, généralement rangé sous l'écologie des populations plutôt que sous l'un des deux noms, a été prolongé dans Organizational Ecology (1993) et Dynamics of Organizational Populations (1992, avec Glenn R. Carroll). Depuis les années 2000, Hannan a réorienté une partie de ses travaux vers l'analyse des catégories et des marchés, notamment dans Concepts and Categories (2019).",
    themes: ["changement-organisationnel"],
    domain: "organizational-sociology",
  },
  {
    id: "beguin",
    slug: "beguin",
    name: "Pascal Béguin",
    tagline:
      "Ce qu'un instrument fige n'est jamais tout à fait figé.",
    keywords: ["Cristallisation", "Plasticité", "Développement"],
    bio: "Pascal Béguin est ergonome, docteur du CNAM (1994) sous la direction d'Alain Wisner, où il enseigne jusqu'en 2006. Il devient ensuite directeur de recherche au département Sciences pour l'action et le développement de l'INRA jusqu'en 2012, avant de rejoindre l'université Lumière Lyon 2 comme professeur d'ergonomie à l'Institut d'études du travail de Lyon. Sa thèse porte sur le passage de l'individuel au collectif dans les activités instrumentées, un terrain qu'il approfondit ensuite avec Pierre Rabardel, dont il est le coauteur. Dans un article de 2007, il distingue trois manières de prendre en compte l'activité en conception : la cristallisation, soit ce qu'un artefact fige d'un modèle de l'utilisateur et qui agit avant même l'usage ; la plasticité, la marge que l'objet laisse à l'appropriation ; et le développement, la transformation de l'activité elle-même par l'usage. Son habilitation, soutenue en 2010, porte sur la conduite de projet et la fabrication collective du travail, dans une approche développementale de la conception.",
    themes: ["activite-instrumentee-et-conception"],
    domain: "activity-ergonomics",
  },
  {
    id: "suppes",
    slug: "suppes",
    name: "Patrick Suppes",
    years: "1922-2014",
    tagline:
      "Un énoncé numérique n'a de sens que s'il résiste au changement d'échelle.",
    keywords: ["Théorie de la mesure", "Invariance", "Théorèmes de représentation"],
    bio: "Patrick Suppes est un philosophe et logicien américain, professeur de philosophie à Stanford, dont l'œuvre couvre la philosophie des sciences, la théorie de la mesure, les fondements de la mécanique quantique et la théorie de la décision. Formé à Chicago puis à Columbia, où il soutient une thèse dirigée par Ernest Nagel, il s'impose comme l'un des architectes de la théorie représentationnelle de la mesure : un système de mesure n'est légitime que s'il existe un théorème de représentation reliant la structure empirique observée à une structure numérique, complété par un théorème d'unicité précisant les transformations qui préservent cette représentation. C'est dans ce cadre qu'il pose, avec un coauteur, le problème de la signification (« meaningfulness problem ») : un énoncé numérique n'a de sens que si sa vérité reste invariante sous les transformations d'échelle admissibles. Suppes a aussi été un pionnier de l'enseignement assisté par ordinateur.",
    themes: ["theorie-des-echelles-et-nombres"],
    domain: "measurement-theory",
  },
  {
    id: "dimaggio",
    slug: "dimaggio",
    name: "Paul J. DiMaggio",
    years: "né en 1951",
    tagline:
      "Ce n'est pas l'efficacité qui uniformise les organisations, mais la légitimité qu'elles recherchent.",
    keywords: ["Isomorphisme institutionnel", "Champ organisationnel", "Légitimité"],
    bio: "Paul J. DiMaggio est un sociologue américain, professeur à Princeton de 1992 à 2016 puis à New York University. Docteur de Harvard, il a consacré ses travaux à la sociologie des organisations, à la sociologie de la culture et aux inégalités sociales. Avec Walter W. Powell, il publie en 1983 « The Iron Cage Revisited », l'un des articles les plus cités des sciences sociales, où les deux auteurs montrent que les organisations d'un même champ tendent à s'homogénéiser non pas parce que cette convergence les rend plus efficaces, mais sous l'effet de trois mécanismes d'isomorphisme institutionnel : la contrainte exercée par des acteurs dont elles dépendent, le mimétisme face à l'incertitude, et la normalisation portée par la professionnalisation. Cette thèse a durablement renouvelé la lecture wébérienne de la « cage de fer » en déplaçant l'explication de la rationalisation bureaucratique vers la recherche de légitimité.",
    themes: ["changement-organisationnel", "bureaucratie-regles"],
    domain: "organizational-sociology",
  },
  {
    id: "cabon",
    slug: "cabon",
    name: "Philippe Cabon",
    tagline:
      "Limiter les heures ne suffit pas ; il faut évaluer le risque que fait courir la fatigue.",
    keywords: ["Fatigue", "Sécurité", "Facteurs humains"],
    bio: "Philippe Cabon est un ergonome français, maître de conférences habilité à diriger des recherches à l'université Paris Cité (ex-Paris Descartes), au sein du Laboratoire de psychologie et d'ergonomie appliquées (LaPEA). Ses recherches, menées depuis plus de vingt ans, portent sur les effets de la privation de sommeil et de la fatigue sur la sécurité et la santé dans les systèmes à risque, en particulier l'aviation. Il s'est notamment intéressé aux systèmes de gestion du risque fatigue (Fatigue Risk Management Systems), une approche qui remplace la simple limitation réglementaire des heures de service par une évaluation continue du risque que la fatigue fait peser sur la sécurité, portée par l'Organisation de l'aviation civile internationale et les autorités australiennes de l'aviation civile. Il en a proposé une lecture critique en contestant l'idée d'un lien linéaire entre niveau de fatigue et niveau de sécurité, à partir de ses propres travaux de recherche.",
    themes: ["charge-et-vigilance"],
    domain: "human-factors",
  },
  {
    id: "falzon",
    slug: "falzon",
    name: "Pierre Falzon",
    years: "né en 1950",
    tagline:
      "Donner les moyens ne suffit pas ; encore faut-il qu'ils deviennent un pouvoir d'agir.",
    keywords: ["Environnement capacitant", "Résilience", "Ergonomie de l'activité"],
    bio: "Pierre Falzon est un psychologue et ergonome français, d'abord chercheur en ergonomie cognitive à l'Inria avant de devenir, en 1991, professeur d'ergonomie et de neurosciences du travail au Cnam, où il succède à Alain Wisner. Il y dirige le Centre de recherches sur le travail et le développement (CRTD) jusqu'en 2017, et préside l'Association internationale d'ergonomie (IEA) entre 2003 et 2006 après en avoir été le secrétaire général. Figure de l'ergonomie de l'activité, il a contribué à déplacer l'analyse du travail vers la question des ressources et des capacités : avec Justine Arnoud, il théorise l'environnement capacitant, cet ensemble de conditions nécessaires pour qu'une ressource mise à disposition se convertisse en pouvoir d'agir réel ; avec Lucie Cuvelier, il propose une lecture de la résilience fondée sur les ressources de l'équipe plutôt que sur le seul respect des protocoles.",
    themes: ["regulation-et-marges", "securite-et-resilience"],
    domain: "activity-ergonomics",
  },
  {
    id: "rabardel",
    slug: "rabardel",
    name: "Pierre Rabardel",
    years: "1945-2021",
    tagline:
      "Un outil ne devient instrument qu'entre les mains de qui s'en sert.",
    keywords: ["Genèse instrumentale", "Schèmes d'utilisation", "Artefact"],
    bio: "Pierre Rabardel est un psychologue et ergonome français, maître de conférences au laboratoire d'ergonomie du CNAM à partir de 1989 puis professeur à l'université Paris 8 de 1993 à 2010. Il est l'artisan principal de l'approche instrumentale en ergonomie cognitive, exposée notamment dans Les hommes et les technologies (1995). Il y montre qu'un artefact — outil, machine, logiciel — ne devient un instrument qu'au terme d'un processus qu'il nomme genèse instrumentale : le sujet s'approprie l'objet en lui associant des schèmes d'utilisation, tout en étant lui-même transformé par cet usage. Cette double orientation, vers l'artefact et vers le sujet, a renouvelé la manière de penser l'activité outillée en ergonomie. Rabardel reprend aussi la notion linguistique de catachrèse, empruntée à la rhétorique, pour désigner l'emploi d'un outil au-delà de sa fonction prévue, et y voit non une erreur à corriger mais la trace d'une contribution des utilisateurs à la conception des usages. Ses travaux ont durablement marqué l'ergonomie francophone de l'activité instrumentée.",
    themes: ["activite-instrumentee-et-conception"],
    domain: "activity-ergonomics",
  },
  {
    id: "hart",
    slug: "hart",
    name: "Sandra G. Hart",
    tagline:
      "Faute de règle pour peser la charge de travail, on la demande à qui la porte.",
    keywords: ["Charge de travail", "NASA-TLX", "Facteurs humains"],
    bio: "Sandra G. Hart est chercheuse au NASA Ames Research Center, où elle a travaillé au sein du Human Performance Research Group sur l'évaluation de la charge de travail mentale des opérateurs — pilotes, contrôleurs aériens, équipages. Son nom reste associé au NASA-TLX (Task Load Index), méthode d'évaluation subjective de la charge de travail mise au point à la NASA Ames au cours des années 1980, aboutissement de plusieurs années de travaux collectifs du laboratoire ; une étude de validation qu'elle a menée avec Lowell E. Staveland est régulièrement citée comme référence de l'outil. Le NASA-TLX combine six sous-échelles — exigence mentale, exigence physique, exigence temporelle, performance, effort et frustration — que l'opérateur note après la tâche et pondère selon l'importance qu'il leur attribue, pour produire un score global de charge de travail. Devenu l'un des instruments les plus utilisés en ergonomie et en facteurs humains, il doit sa diffusion à la simplicité de sa passation autant qu'à l'origine institutionnelle du travail dont il est issu. Hart a poursuivi ses recherches à la NASA sur la charge de travail et la performance humaine dans l'aviation.",
    themes: ["charge-et-vigilance"],
    domain: "human-factors",
  },
  {
    id: "caroly",
    slug: "caroly",
    name: "Sandrine Caroly",
    years: "née en 1971",
    tagline:
      "Un collectif de travail se construit ; il ne va pas de soi.",
    keywords: ["Collectif de travail", "Prévention des risques", "Activité collective"],
    bio: "Sandrine Caroly est professeure d'ergonomie à l'université Grenoble Alpes, enseignant notamment à Grenoble INP et rattachée au laboratoire PACTE. Ses recherches portent sur l'activité collective de travail, la prévention des risques professionnels, l'organisation du travail et les questions de genre en santé au travail, dans des secteurs variés (services, industrie, petites entreprises). Elle a contribué à préciser la distinction entre travail collectif — la façon dont plusieurs personnes s'organisent concrètement pour accomplir ensemble une tâche — et collectif de travail, construction plus exigeante qui suppose transmission des règles de métier, entraide et confiance réciproque, et qui protège la santé de ceux qui la composent. Elle formule d'abord cette distinction avec Yves Clot en 2004, puis la reprend en 2007 avec Annie Weill-Fassina, dans la continuité d'une réflexion sur le collectif de travail antérieure à ses propres travaux. Sandrine Caroly a également exercé des responsabilités institutionnelles à Grenoble INP, notamment sur l'égalité femmes-hommes.",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "stevens",
    slug: "stevens",
    name: "Stanley Smith Stevens",
    years: "1906-1973",
    tagline:
      "Numéroter n'est pas encore mesurer : tout dépend de la règle.",
    keywords: ["Échelles de mesure", "Psychophysique", "Loi de puissance"],
    bio: "Stanley Smith Stevens est un psychologue américain, professeur à Harvard où il fonde et dirige le Psycho-Acoustic Laboratory. Pionnier de la psychophysique, il est connu pour la loi de puissance qui porte son nom, décrivant la relation entre l'intensité d'un stimulus physique et l'intensité perçue par un sujet. Dans un article de 1946, « On the Theory of Scales of Measurement », il propose une classification des échelles de mesure en quatre niveaux — nominale, ordinale, à intervalles et de rapports —, chacun défini par les opérations empiriques qui le fondent et par les transformations qui le laissent invariant. Il y reprend, en la citant, une définition déjà esquissée par le physicien N. R. Campbell, et mentionne avoir bénéficié d'une discussion avec le mathématicien G. D. Birkhoff pour la mise au point de sa classification, présentée dès 1941. Devenue un point de passage obligé de l'enseignement des statistiques, cette typologie ne dicte pas, selon Stevens lui-même, l'usage exclusif d'une statistique pour chaque échelle. Il a aussi dirigé le volumineux Handbook of Experimental Psychology (1951).",
    themes: ["theorie-des-echelles-et-nombres"],
    domain: "measurement-theory",
  },
  {
    id: "sheridan",
    slug: "sheridan",
    name: "Thomas B. Sheridan",
    years: "né en 1929",
    tagline:
      "Entre l'humain qui agit et la machine qui décide, dix degrés possibles.",
    keywords: ["Contrôle supervisé", "Télérobotique", "Automatisation"],
    bio: "Thomas B. Sheridan est un ingénieur américain, professeur émérite de génie mécanique et de psychologie appliquée au MIT, où il a mené l'essentiel de sa carrière à partir de 1959. Pionnier de la robotique et de la téléopération, il s'est attaché à comprendre comment un opérateur humain peut piloter un système à distance ou en partage avec un ordinateur, plutôt que de tout commander lui-même ou de tout déléguer à la machine. Avec William L. Verplank, il propose en 1978, dans un rapport du MIT, une échelle graduant les degrés d'automatisation possibles entre contrôle manuel intégral et autonomie complète de la machine. La même année, il cosigne avec Verplank et Thurston L. Brooks une communication sur le contrôle supervisé de téléopérateurs sous-marins. Ses travaux ont fondé le champ du contrôle supervisé (supervisory control), aujourd'hui central en ergonomie et en facteurs humains.",
    themes: ["automatisation-et-conception-cognitive"],
    domain: "human-factors",
  },
  {
    id: "brooks",
    slug: "brooks",
    name: "Thurston L. Brooks",
    tagline:
      "Faire remonter un plongeur, ou faire descendre une machine supervisée.",
    keywords: ["Téléopération sous-marine", "Contrôle supervisé", "SUPERMAN"],
    bio: "Thurston L. Brooks est un ingénieur ayant travaillé au MIT à la fin des années 1970 sur la téléopération en milieu sous-marin. Ses recherches, menées dans le cadre du Man-Machine Systems Laboratory, portent sur les limites des plongeurs humains dans les environnements océaniques profonds et sur la manière dont des systèmes commandés par ordinateur peuvent étendre ou remplacer leurs capacités de manipulation. Il décrit notamment un système de téléopérateur à contrôle supervisé baptisé SUPERMAN. En novembre 1978, il cosigne avec Thomas B. Sheridan et William L. Verplank une communication présentée à la 14e conférence annuelle sur le contrôle manuel, intitulée « Human/computer control of undersea teleoperators ». Sa contribution reste circonscrite à ces travaux sur la téléopération sous-marine ; le détail de son parcours ultérieur est peu documenté.",
    themes: ["automatisation-et-conception-cognitive"],
    domain: "human-factors",
  },
  {
    id: "powell",
    slug: "powell",
    name: "Walter W. Powell",
    years: "né en 1951",
    tagline:
      "Pourquoi les organisations qui se cherchent finissent-elles par se ressembler ?",
    keywords: ["Isomorphisme institutionnel", "Nouvel institutionnalisme", "Réseaux organisationnels"],
    bio: "Walter W. Powell est un sociologue américain, professeur à l'université Stanford, formé à SUNY Stony Brook auprès notamment de Charles Perrow et Mark Granovetter. Avec Paul J. DiMaggio, il publie en 1983 « The Iron Cage Revisited : Institutional Isomorphism and Collective Rationality in Organizational Fields », l'un des articles les plus cités de la sociologie des organisations. Les deux auteurs y montrent que les organisations d'un même champ tendent à converger vers des structures et pratiques semblables non pas parce que celles-ci seraient plus efficaces, mais sous l'effet de trois mécanismes : la contrainte exercée par des acteurs dont elles dépendent, l'imitation d'organisations jugées légitimes face à l'incertitude, et la professionnalisation qui diffuse des normes communes. Ce travail, toujours attribué conjointement à DiMaggio et Powell, a fondé le courant du nouvel institutionnalisme. Powell a également étudié les formes réticulaires d'organisation, distinctes du marché et de la hiérarchie.",
    themes: ["changement-organisationnel", "bureaucratie-regles"],
    domain: "organizational-sociology",
  },
  {
    id: "espeland",
    slug: "espeland",
    name: "Wendy Nelson Espeland",
    tagline:
      "Une mesure publique ne décrit pas seulement : elle transforme ce qu'elle mesure.",
    keywords: ["Réactivité", "Commensuration", "Classements"],
    bio: "Wendy Nelson Espeland est une sociologue américaine, professeure à l'université Northwestern, dont les travaux portent sur les organisations, la culture, le droit et la quantification. Avec Michael Sauder, elle étudie comment les classements médiatiques ont transformé l'enseignement du droit aux États-Unis, dans « Fear of Falling » (2015). Reprenant et élargissant la notion de réactivité forgée par Donald T. Campbell puis développée par Carol A. Heimer, elle montre, avec Sauder, qu'une mesure publique comme un classement n'est jamais neutre : les acteurs évalués s'ajustent à ce qui les évalue, par autoréalisation des prédictions et par commensuration, c'est-à-dire la traduction de qualités en quantités comparables. Ce cadre distingue trois effets typiques des classements : maximiser son rang, redéfinir ce qu'on fait pour mieux y correspondre, ou manipuler directement les données transmises. Avec Mitchell L. Stevens, elle a aussi publié un article fondateur sur la commensuration comme processus social (1998).",
    themes: ["effets-retour-de-la-mesure"],
    domain: "measurement-theory",
  },
  {
    id: "verplank",
    slug: "verplank",
    name: "William L. Verplank",
    tagline:
      "Entre l'humain et la machine, l'autorité se règle par degrés.",
    keywords: ["Contrôle supervisé", "Degrés d'automatisation", "Interaction design"],
    bio: "William L. Verplank est un chercheur et designer américain, l'un des pionniers de l'interaction homme-machine. Formé en ingénierie mécanique à Stanford puis en « man-machine systems » au MIT sous la direction de Thomas B. Sheridan, il a travaillé chez Xerox PARC (1978-1986) sur les interfaces graphiques et la souris de la station Xerox Star, avant de rejoindre Bill Moggridge chez IDtwo puis IDEO, puis de diriger des recherches à Interval Research. Avec Moggridge, on lui attribue la paternité du terme « interaction design ». Son nom reste associé, avec celui de Sheridan, à l'échelle des dix degrés d'automatisation formulée dans un rapport du MIT de 1978 : une graduation des rôles possibles entre l'humain qui planifie et surveille et la machine qui exécute, du contrôle manuel intégral à l'automatisation complète. Popularisée sous le nom de « contrôle supervisé », cette échelle est devenue une référence pour penser les degrés d'autonomie des systèmes automatisés, bien au-delà de son champ d'origine, l'aéronautique et la téléopération.",
    themes: ["automatisation-et-conception-cognitive"],
    domain: "human-factors",
  },
  {
    id: "cuny",
    slug: "cuny",
    name: "Xavier Cuny",
    years: "né en 1935",
    tagline:
      "Poser, avec Leplat, le schéma qui allait nourrir toute une discipline.",
    keywords: ["Régulation de l'activité", "Analyse des accidents du travail", "Prise de risque"],
    bio: "Xavier Cuny est un psychologue français associé au Conservatoire national des arts et métiers, où il a enseigné la sécurité et la prévention des risques professionnels. Avec Jacques Leplat, il cosigne en 1977 « Introduction à la psychologie du travail », un ouvrage qui a structuré la discipline en France et où figure le schéma à deux boucles de régulation de l'activité — celle qui ajuste l'écart entre but et résultat, et celle par laquelle l'opérateur, sous contrainte, se modifie lui-même. Ses propres travaux portent surtout sur l'analyse des accidents du travail : dès 1970, avec Krawsky, il publie dans Le Travail Humain une approche socio-technique de l'accident, prolongée en 1972 par une méthode pratique de recherche des facteurs d'accident coécrite avec Krawsky et Monteau pour l'INRS. Il codirige aussi avec Pierre Goguelin un ouvrage collectif sur la prise de risque dans le travail (1989), thème qui prolonge directement la question de la régulation de l'activité en situation contrainte.",
    themes: ["regulation-et-marges"],
    domain: "activity-ergonomics",
  },
  {
    id: "clot",
    slug: "clot",
    name: "Yves Clot",
    years: "né en 1952",
    tagline:
      "Ce qui ne s'est pas fait pèse aussi sur le travail.",
    keywords: ["Clinique de l'activité", "Réel de l'activité", "Genre professionnel"],
    bio: "Yves Clot est professeur émérite de psychologie du travail au Conservatoire national des arts et métiers (Cnam), où il a fondé et longtemps dirigé l'équipe de clinique de l'activité au sein du Centre de recherche sur le travail et le développement (CRTD). Arrivé à la chaire de psychologie du travail du Cnam au début des années 1990 aux côtés de Christophe Dejours, il s'impose comme l'un des principaux introducteurs en France de l'œuvre de Lev Vygotski, dont il tire l'idée que l'activité déborde toujours ce qui s'en observe. Il forge la notion de réel de l'activité pour désigner ce volume caché sous l'activité réalisée, et, avec Daniel Faïta, celle de genre professionnel : ces manières de faire tacites propres à un métier, que chaque travailleur retouche à sa façon en y imprimant son style. Ses travaux ont profondément renouvelé la clinique du travail et la réflexion sur la santé au travail et le pouvoir d'agir. Il a reçu en 2011 le prix du meilleur ouvrage sur le monde du travail pour « Le Travail à cœur ».",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
  {
    id: "schwartz",
    slug: "schwartz",
    name: "Yves Schwartz",
    years: "né en 1942",
    tagline:
      "Travailler, c'est toujours retravailler la norme qu'on vous donne.",
    keywords: ["Ergologie", "Débats de normes", "Usage de soi"],
    bio: "Yves Schwartz, né à Marseille, est un philosophe français, professeur émérite de l'Université d'Aix-Marseille, où il a fondé au début des années 1980 un dispositif d'analyse pluridisciplinaire des situations de travail devenu l'Institut d'ergologie. Agrégé de philosophie en 1967 devant un jury présidé par Georges Canguilhem, il a fait du travail, et plus largement de l'activité humaine, l'objet central de sa réflexion, dans une démarche qu'il nomme l'ergologie et qui associe savoirs disciplinaires et savoirs d'expérience des travailleurs eux-mêmes. Il reprend à Canguilhem l'idée que la santé se joue dans un débat entre des normes venues du milieu et celles que le vivant cherche à imposer, et forge la notion de débats de normes pour décrire la manière dont quiconque travaille renormalise sans cesse les prescriptions qu'il reçoit. Il développe aussi le concept d'usage de soi, par lequel le travailleur est à la fois usé par son activité et sujet usant de lui-même. Il est membre correspondant de l'Académie des sciences morales et politiques depuis 2017.",
    themes: ["activite-empechee-et-metier"],
    domain: "activity-ergonomics",
  },
];
